### PR TITLE
Use parallel_for_ to replace multicore switch

### PR DESCRIPTION
**Pull request by charmoniumQ**
This uses `parallel_for_` instead of `boost:thread`. This has three advantages:

1. No need to maintain two versions of the same code (one parallel, one sequential). One `parallel_for_` can be run with or without parallelism.
2. No need to pass around `use_multicore`. `cv::setNumThreads` globally controls whether parallelism is used.
3. It does not create/destroy threads while running. The old code created/destroyed tens of thousands of threads. This results in lower performance and throws off analysis (like perf and NVIDIA NSight Computer).

### CODE REVIEW

**Comment by goldbattle** [comment]
Thanks for the PR! Seem like it would be nice to remove the boost::threads as it seems have have some drawbacks. I will try to find time to review (along with the other issues I need to address on the repo). If you are able to debug why the CI is failing that would help me out and ensure that people are able to use the project out of the box.

I see that you included a dockerfile. Is this necessary?

**Comment by charmoniumQ** [comment]
Thanks for the quick response. I fixed the CI. Dumb copy/pasting mistake.

The Dockerfile is not necessary. I can delete it, but I thought that other users might benefit from it. It makes it easier to test OpenVINS without installing ROS to one's physical machine.

**Comment by goldbattle** [comment]
You will likely need to use the `LambdaBody` to have it compile on all platforms.
https://github.com/rpng/open_vins/blob/master/ov_core/src/track/Grider_FAST.h#L37-L52

I am fine with adding a dockerfile if you provide a small guide / information on how to use and develop with it (or a link to a website that I can use as a reference). I would want to add a documentation page for those coming to the project and want to use it.

**Comment by charmoniumQ** [comment]
`LambdaBody` problem is fixed.

**Comment by goldbattle** [comment]
Thanks, I will be able to merge later part of next week after ICRA wraps up.
Thanks again for the PR.
This should close issue #166 .
Do you have any number to the overhead of the thread creation / old boost thread method?

**Comment by charmoniumQ** [comment]
On my machine, thread setup/teardown costs 25us. You can do your own timing [here](https://gist.github.com/charmoniumQ/82453fe5afd07eca72d247be5d93d8f9).

I think the bigger sell is that it makes performance much easier to analyze using tools like NSight Systems and perf.

**Pull request merged**
